fix pre publish checks 6

diff --git a/.github/workflows/sdk_checks.yaml b/.github/workflows/sdk_checks.yaml
--- a/.github/workflows/sdk_checks.yaml
+++ b/.github/workflows/sdk_checks.yaml
@@ -85,6 +85,15 @@ jobs:
       - run: uv lock --check
   checks-complete:
     needs: [ruff-check, ruff-format, basedpyright, dprint, markdownlint, uv-lock]
+    if: always()
     runs-on: ubuntu-latest
     steps:
-      - run: echo "All checks passed"
+      - name: Check tests result
+        if: ${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && !contains(needs.*.result, 'skipped') }}
+        run: echo "✅ All tests passed"
+
+      - name: Fail if any test failed
+        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}
+        run: |
+          echo "❌ Some tests failed, were cancelled, or were skipped"
+          exit 1
diff --git a/.github/workflows/sdk_tests.yaml b/.github/workflows/sdk_tests.yaml
--- a/.github/workflows/sdk_tests.yaml
+++ b/.github/workflows/sdk_tests.yaml
@@ -141,6 +141,15 @@ jobs:
           retention-days: 7
   tests-complete:
     needs: [pytest, pytest-after-build]
+    if: always()
     runs-on: ubuntu-latest
     steps:
-      - run: echo "All tests passed"
+      - name: Check tests result
+        if: ${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && !contains(needs.*.result, 'skipped') }}
+        run: echo "✅ All tests passed"
+
+      - name: Fail if any test failed
+        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}
+        run: |
+          echo "❌ Some tests failed, were cancelled, or were skipped"
+          exit 1
